name: rescue_odyssey
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.14.0
  flame_tiled: ^1.18.3
  jenny: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/characters/arturo_bird/
    - assets/images/characters/arturo_boy/
    - assets/images/dialogue_box/
    - assets/images/logos/
    - assets/images/backgrounds/
    - assets/images/world_tiles/prelude/
    - assets/tiles/
    - assets/yarn/

  fonts:
    - family: Yoster
      fonts:
        - asset: fonts/Yoster_Font.ttf
